url: "tasnia-hussain.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl:
title: "Tasnia Hussain" # the name of your site, e.g. ACME Corp.
description: "Academic Resume"
theme: academic-jekyll-theme