url: "https://www.gabriel-lipkowitz.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Gabriel Lipkowitz" # the name of your site, e.g. ACME Corp.
description: "PhD Student at Stanford University"
